import { Component, Input } from '@angular/core';
import { IonIcon } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  homeOutline,
  compassOutline,
  calendarOutline,
  chatbubbleEllipsesOutline,
  personOutline,
  peopleOutline,
  notificationsOutline,
  searchOutline,
  locationOutline,
  addOutline,
  arrowForwardOutline,
  arrowBackOutline,
  chevronForwardOutline,
  chevronBackOutline,
  chevronDownOutline,
  basketballOutline,
  footballOutline,
  tennisballOutline,
  fitnessOutline,
  gameControllerOutline,
  flagOutline,
  timeOutline,
  closeOutline,
  checkmarkOutline,
  checkmarkCircleOutline,
  settingsOutline,
  logOutOutline,
  heartOutline,
  shareSocialOutline,
  sendOutline,
  shieldCheckmarkOutline,
  trophyOutline,
  flashOutline,
  gridOutline,
  optionsOutline,
  ellipsisHorizontal,
  lockClosedOutline,
  eyeOutline,
  mailOutline,
  barChartOutline,
  warningOutline,
  personAddOutline,
  peopleCircleOutline,
  sunnyOutline,
  reloadOutline,
  baseballOutline,
  imageOutline,
} from 'ionicons/icons';
addIcons({
  homeOutline,
  compassOutline,
  calendarOutline,
  chatbubbleEllipsesOutline,
  personOutline,
  peopleOutline,
  notificationsOutline,
  searchOutline,
  locationOutline,
  addOutline,
  arrowForwardOutline,
  arrowBackOutline,
  chevronForwardOutline,
  chevronBackOutline,
  chevronDownOutline,
  basketballOutline,
  footballOutline,
  tennisballOutline,
  fitnessOutline,
  gameControllerOutline,
  flagOutline,
  timeOutline,
  closeOutline,
  checkmarkOutline,
  checkmarkCircleOutline,
  settingsOutline,
  logOutOutline,
  heartOutline,
  shareSocialOutline,
  sendOutline,
  shieldCheckmarkOutline,
  trophyOutline,
  flashOutline,
  gridOutline,
  optionsOutline,
  ellipsisHorizontal,
  lockClosedOutline,
  eyeOutline,
  mailOutline,
  barChartOutline,
  warningOutline,
  personAddOutline,
  peopleCircleOutline,
  sunnyOutline,
  reloadOutline,
  imageOutline,
});
addIcons({
  baseballOutline,
  'volleyball-outline':
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><g fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="16" cy="16" r="13"/><path d="M16 3c0 7 5 11 12 13M5 9c7-3 12-2 17 4M8 26c0-8 4-12 12-15M3 16c4 4 9 5 14 4M26 24c-5-1-8-5-9-11M16 29c2-6 1-11-3-15"/></g></svg>',
});
@Component({
  selector: 'g-icon',
  standalone: true,
  imports: [IonIcon],
  template: '<ion-icon [name]="name" aria-hidden="true" />',
})
export class IconComponent {
  @Input() name = 'basketball-outline';
}
