import { readFile, mkdir, writeFile } from 'node:fs/promises';
const sources = await Promise.all(
  ['server/src/database/seed.ts', 'database/seeds/sports.sql'].map((p) => readFile(p, 'utf8')),
);
const ids = [...new Set(sources.join('\n').match(/photo-\d+-[a-z0-9]+/g))];
await mkdir('public/images', { recursive: true });
const downloaded = [];
const errors = [];
for (let i = 0; i < ids.length; i += 4) {
  await Promise.all(
    ids.slice(i, i + 4).map(async (id) => {
      try {
        const response = await fetch(
          `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=80`,
          { signal: AbortSignal.timeout(40000) },
        );
        if (!response.ok) throw new Error(String(response.status));
        const data = new Uint8Array(await response.arrayBuffer());
        if (data.length < 1000) throw new Error('Empty image');
        await writeFile(`public/images/${id}.jpg`, data);
        downloaded.push(id);
      } catch (e) {
        errors.push(`${id}: ${e.message}`);
      }
    }),
  );
}
await writeFile(
  'src/app/shared/photo-manifest.ts',
  `// Local copies of the development sample photographs. Generated by scripts/download-assets.mjs.\nexport const localPhotoIds = new Set(${JSON.stringify(downloaded, null, 2)});\n`,
);
console.log(`Saved ${downloaded.length} local photographs.`);
if (errors.length) console.log('Remote fallbacks retained for:', errors.join('\n'));
